### ISSUE TITLE
Why does the nest submodule refer to some old commit from stdp_izh_connection?

### ISSUE THREAD

**Issue by aserenko** [INM-6/reproducing-polychronization#3]
Currently, the nest submodule is checked out at commit [5606b4b](https://github.com/weidel-p/nest-simulator/tree/5606b4b29f89222d733f1475ffd5648b7b4dd6c9) from https://github.com/weidel-p/nest-simulator/tree/feature/stdp_izh_connection. However, that `stdp_izh_connection` branch had months of updates since then, from February 2018 till April 2018. Were those updates really unrelated to your paper, or maybe they were just forgotten to check out here?

**Comment by clinssen** [comment]
Hi @aserenko! I just tried a fresh clone and submodule init of the repo, and it checks out the latest commit on https://github.com/weidel-p/nest-simulator/tree/feature/stdp_izh_connection for me (7f52bd5ae), which seems consistent with the contents of the .gitmodules file. Could you double-check with a fresh clone? I don't understand where [5606b4b](https://github.com/weidel-p/nest-simulator/tree/5606b4b29f89222d733f1475ffd5648b7b4dd6c9) could come from.

**Comment by aserenko** [comment]
My mistake, sorry! I ran `git submodule update` without `--remote`.

As a side note, regarding
> I don't understand where [5606b4b](https://github.com/weidel-p/nest-simulator/tree/5606b4b29f89222d733f1475ffd5648b7b4dd6c9) could come from.

As far as I understand, the current head of a submodule does not get registered in the `.gitmodules` file, it gets committed as a directory entry. And currently, yours is pointing to 5606b4b, as can be seen just by opening https://github.com/INM-6/reproducing-polychronization/tree/master/code/nest in your browser. I just was misled by that.
